### ISSUE TITLE
Base64Url::decode function

### ISSUE THREAD

**Issue by muneeb706** [Spomky-Labs/base64url#14]
Base64Url::decode(string $data) works for some base64 strings but throws invalid data for others.
For example:
It throws invalid data exception for the following strings:
BP0zm+/ZFSYCDt4p51CFCEhpZ0gNySeAJPv3z9rHRsu5/YNlKg5nP3Rhrp6WUt3xdI7GFaZREP3Ld4LYHE26Eyg=
BPqkO1/Lox1q4vWmnAniO4DRcFE0T6EIjPZcjKXvMpKU4TxosZOUPpqQNIUCJxvHsSEWCFKC0fwj7NPlLzC8g94=

and works for following strings:
BCT5o8/IyYueBdumhkt5mQSf35obGPjljxl1ayUzoL0R4UM4Fa2YIrRecKlBUC8ODO309WdpcM3MrwA/ynPh0g0=
BAw3DLU58S2H1JOZBAtYtSuKUi4lVQojO6Av6WRo519gpk1Taxd8BlNeRspM1jEK2MBTemn0jCOJ2l/2MncL98c=

Why the behavior is random? All of the above are valid base64 strings.

Thanks

**Comment by Spomky** [comment]
Hi @muneeb706,

I am sorry to read that you have some troubles with this library, but it works fine with all samples you mentioned

See this sandbox: https://phpsandbox.io/e/x/falling-disk-pgnp

**Comment by muneeb706** [comment]
This function is being used by [https://github.com/web-push-libs/web-push-php](web-push-php). I was using it via this library.  Possibly this library corrupts the string in the middle.  I will look for it.
Thanks.
